name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: '26'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
