name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test
    strategy:
      matrix:
        node: [ '18', '20', '22', '24', '26' ]
